export default [
	{
		key: 1,
		name: 'Portfolio',
		languages: ['ReactJS, HTML, TailwindCSS, Motion, Toastify'],
		sitelink: 'https://braydenfriesen.com/',
		repolink: 'https://github.com/Be-Freezin/Brayden-Portfolio-Official',
		projectimage: '/project-imgs/code-project.jpg',
		projectDescription: 'My personal portfolio site. Filled with personality and curiosities. The primary objective of this project was to have a place i can showcase my projects and tell a story. Keeping it clean and minimal with my personality injected into it while remaining professional and light hearted. The projected was designed and created by me.',
		siteicon: '/site-icons/livesite.png',
		repoicon: '/site-icons/repo.png',
	},
	{
		key: 2,
		name: 'Elden Ring Build Maker',
		languages: ['ReactJS, HTML, TailwindCSS'],
		sitelink: 'https://cheerful-syrniki-d189ba.netlify.app/',
		repolink: 'https://github.com/Be-Freezin/elden-ring',
		projectimage: '/project-imgs/gaming-project.jpg',
		projectDescription: 'The primary objective of this site was to showcase i can consume APIs and display the data from them. The project is used to help people create solid starting points for one of my favorite games, Elden Ring. This project is in continuous development and will one day get completed. Elden Ring has complex calculations and my main goal was to give users a starting point to help guid them on creating a build.',
		siteicon: '/site-icons/livesite.png',
		repoicon: '/site-icons/repo.png',
	},
	{
		key: 3,
		name: 'Password Generator',
		languages: ['Javascript, HTML, CSS'],
		sitelink: 'https://be-freezin.github.io/Password-Generator/',
		repolink: 'https://github.com/Be-Freezin/Password-Generator',
		projectimage: '/project-imgs/PasswordProject.jpg',
		projectDescription: "One of the first Javascript projects i made when i started my learning journey. It is by no means meant to have the security to be used in real life. It can be used to generate a random string of characters that can be copied and used anywhere. The passwords don't get stored into any database.",
		siteicon: '/site-icons/livesite.png',
		repoicon: '/site-icons/repo.png',
	},
	{
		key: 4,
		name: 'Jaryn Friesen',
		languages: ['Javascript, HTML, CSS'],
		sitelink: 'https://www.jarynfriesen.com/',
		repolink: 'https://github.com/Be-Freezin/Jaryn-Frisen-Website-FINAL',
		projectimage: '/project-imgs/JF-2.jpg',
		projectDescription: "My first website ever created for a client. The priomary objective for this was to give the customer an online presence and allow them to treat this as a business card and send to promoters. He's actually gotten several gigs by showing people his website!",
		siteicon: '/site-icons/livesite.png',
		repoicon: '/site-icons/repo.png',
	},
]
