export default [
	{
		key: 1,
		name: 'Portfolio',
		languages: ['ReactJS, HTML, TailwindCSS'],
		sitelink: 'https://braydenfriesen.com/',
		repolink: 'https://github.com/Be-Freezin/Brayden-Portfolio-Official',
		projectimage: '/project-imgs/code-project.jpg',
		siteicon: '/site-icons/livesite.png',
		repoicon: '/site-icons/repo.png',
	},
	{
		key: 2,
		name: 'Elden Ring Build Maker',
		languages: ['ReactJS, HTML, TailwindCSS'],
		sitelink: 'https://cheerful-syrniki-d189ba.netlify.app/',
		repolink: 'https://github.com/Be-Freezin/elden-ring',
		projectimage: '/project-imgs/gaming-project.jpg',
		siteicon: '/site-icons/livesite.png',
		repoicon: '/site-icons/repo.png',
	},
	{
		key: 3,
		name: 'Password Generator',
		languages: ['Javascript, HTML, CSS'],
		sitelink: 'https://be-freezin.github.io/Password-Generator/',
		repolink: 'https://github.com/Be-Freezin/Password-Generator',
		projectimage: '/project-imgs/PasswordProject.jpg',
		siteicon: '/site-icons/livesite.png',
		repoicon: '/site-icons/repo.png',
	},
	{
		key: 4,
		name: 'Musician Website',
		languages: ['Javascript, HTML, CSS'],
		sitelink: 'https://www.jarynfriesen.com/',
		repolink: 'https://github.com/Be-Freezin/Jaryn-Frisen-Website-FINAL',
		projectimage: '/project-imgs/JF-2.jpg',
		siteicon: '/site-icons/livesite.png',
		repoicon: '/site-icons/repo.png',
	},
]
