export default [
	{
		key: 1,
		name: 'Portfolio',
		languages: ['ReactJS, HTML, TailwindCSS'],
		sitelink: 'www.linkhere.com',
		repolink: 'www.repohere.com',
		projectimage: '/project-imgs/code-project.jpg',
		siteicon: '/site-icons/livesite.png',
		repoicon: '/site-icons/repo.png',
	},
	{
		key: 2,
		name: 'Elden Ring Build Maker',
		languages: ['ReactJS, HTML, TailwindCSS'],
		sitelink: 'https://cheerful-syrniki-d189ba.netlify.app/',
		repolink: 'https://github.com/Be-Freezin/elden-ring',
		projectimage: '/project-imgs/gaming-project.jpg',
		siteicon: '/site-icons/livesite.png',
		repoicon: '/site-icons/repo.png',
	},
	// {
	// 	key: 3,
	// 	name: 'Portfolio',
	// 	languages: ['ReactJS, HTML, TailwindCSS'],
	// 	sitelink: 'www.linkhere.com',
	// 	repolink: 'www.repohere.com',
	// 	projectimage: '/project-imgs/code-project.jpg',
	// 	siteicon: '/site-icons/livesite.png',
	// 	repoicon: '/site-icons/repo.png',
	// },
	// {
	// 	key: 4,
	// 	name: 'Portfolio',
	// 	languages: ['ReactJS, HTML, TailwindCSS'],
	// 	sitelink: 'www.linkhere.com',
	// 	repolink: 'www.repohere.com',
	// 	projectimage: '/project-imgs/code-project.jpg',
	// 	siteicon: '/site-icons/livesite.png',
	// 	repoicon: '/site-icons/repo.png',
	// },
]
